sport/core/urls.py
from django.urls import path
from . import views
from django.views.generic import DetailView



app_name = 'core'
urlpatterns = [
    path('', views.index, name='index'),
    #path('<int:pk>', views.detailprogramme, name='detailpro'),
    path('gallery/', views.gallery, name='gallery'),
    path('trainer/', views.trainer, name='trainer'),
    path('pricing/', views.pricing, name='pricing'),
    path('blog/', views.blog, name='blog'),
    path('blog/<int:pk>', views.detail, name='detail'),
    path('blog/search', views.search, name='search'),
    path('contact/', views.contact, name='contact'),
    path('login/', views.loginPage, name='login'),
    path('logout/', views.loginPage, name='logout'),
    path('register/', views.registerPage, name='register')


]

sport/sport/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("core.urls")),
]

if settings.DEBUG:
   urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
   urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sport/templates/parts/footer.html
{% load static %}
<footer id="fh5co-footer" class="fh5co-bg" style="background-image: url({% static '/images/img_bg_1.jpg' %});" role="contentinfo">
		<div class="overlay"></div>
		<div class="container">
			<div class="row row-pb-md">
				<div class="col-md-4 fh5co-widget">
					<h3>A Little About Stamina.</h3>
					<p>Facilis ipsum reprehenderit nemo molestias. Aut cum mollitia reprehenderit. Eos cumque dicta adipisci architecto culpa amet.</p>
					<p><a class="btn btn-primary" href="#">Become A Member</a></p>
				</div>
				<div class="col-md-8">
					<h3>Classes</h3>
					<div class="col-md-4 col-sm-4 col-xs-6">
						<ul class="fh5co-footer-links">
							<li><a href="#">Cardio</a></li>
							<li><a href="#">Body Building</a></li>
							<li><a href="#">Yoga</a></li>
							<li><a href="#">Boxing</a></li>
							<li><a href="#">Running</a></li>
						</ul>
					</div>

					<div class="col-md-4 col-sm-4 col-xs-6">
						<ul class="fh5co-footer-links">
							<li><a href="#">Boxing</a></li>
							<li><a href="#">Martial Arts</a></li>
							<li><a href="#">Karate</a></li>
							<li><a href="#">Kungfu</a></li>
							<li><a href="#">Basketball</a></li>
						</ul>
					</div>

					<div class="col-md-4 col-sm-4 col-xs-6">
						<ul class="fh5co-footer-links">
							<li><a href="#">Badminton</a></li>
							<li><a href="#">Body Building</a></li>
							<li><a href="#">Teams</a></li>
							<li><a href="#">Advertise</a></li>
							<li><a href="#">API</a></li>
						</ul>
					</div>
				</div>
			</div>

			<div class="row copyright">
				<div class="col-md-12 text-center">
					<p>
						<small class="block">&copy; 2016 Free HTML5. All Rights Reserved.</small>
						<small class="block">Designed by <a href="http://freehtml5.co/" target="_blank">FreeHTML5.co</a> Demo Images: <a href="http://unsplash.co/" target="_blank">Unsplash</a></small>
					</p>
					<p>
						<ul class="fh5co-social-icons">
							<li><a href="#"><i class="icon-twitter"></i></a></li>
							<li><a href="#"><i class="icon-facebook"></i></a></li>
							<li><a href="#"><i class="icon-linkedin"></i></a></li>
							<li><a href="#"><i class="icon-dribbble"></i></a></li>
						</ul>
					</p>
				</div>
			</div>

		</div>
	</footer>

sport/templates/parts/header.html
{% load static %}
{% load app_tags %}
{% get_menus as menus %}
<style>
	.hello-msg{
		font-size: 18px;
		color: #000000;
		margin-right: 20px;
	}
</style>
<div id="page">
<nav class="fh5co-nav" role="navigation">
	<div class="top">
		<div class="container">
			<div class="row">
				<div class="col-xs-12 text-right">
					<p class="num">Call: +01 123 456 7890</p>
					<ul class="fh5co-social">
						<li><a href="#"><i class="icon-twitter"></i></a></li>
						<li><a href="#"><i class="icon-dribbble"></i></a></li>
						<li><a href="#"><i class="icon-github"></i></a></li>
					</ul>
				</div>
			</div>
		</div>
	</div>
	<div class="top-menu">
		<div class="container">
			<div class="row">
				<div class="col-xs-2">
					<div id="fh5co-logo"><a href="index.html">Stamina<span>.</span></a></div>
				</div>
				<div class="col-xs-10 text-right menu-1">
					<ul>
						{% for item in menus %}
						<li><a href="{{ item.link }}">{{ item.name }}</a></li>
						{% endfor %}
						<span class="hello-msg">Hello , {{ request.user }}</span>
				<span class="hello-msg"><a href="{% url 'core:logout'%}">Logout</a></span>

					</ul>
				</div>

			</div>

		</div>
	</div>
</nav>